### PR TITLE
Adds version flag to software which is printed on startup.

### PR DESCRIPTION
**Pull request by nwaldispuehl**
This is supposed to transfer the tag (e.g. `v1.2.3`) and the commit hash (e.g. `ab123cd...`) into the software on compile time and print it to the log on software start like this:
```
INFO[0000]main.go:85 wg-access-server v1.2.3 (ab123cd) 
```
Since we're only deploying images from the `master` branch and from the tags, this should properly reflect the current state of the version.

~This PR is mainly to test if it actually works with the actions.~ -> This appears to [work](https://github.com/freifunkMUC/wg-access-server/actions/runs/5458316418/jobs/9933278562):
```
#26 [server 14/15] RUN echo "Using: Version: feature/add-version-flag, Commit: 13608d43759ec2b7a36ddc338fc3583a956eaba9"
#26 0.079 Using: Version: feature/add-version-flag, Commit: 13608d43759ec2b7a36ddc338fc3583a956eaba9
#26 DONE 0.1s

#27 [server 15/15] RUN go build -o wg-access-server -ldflags="-X 'github.com/freifunkMUC/wg-access-server/buildinfo.Version=feature/add-version-flag' -X 'github.com/freifunkMUC/wg-access-server/buildinfo.CommitHash=13608d43759ec2b7a36ddc338fc3583a956eaba9'"
#27 DONE 80.5s
```

### CODE REVIEW

**Comment by nwaldispuehl** [comment]
Additionally added the newly introduced build information to the GRPC message sent to the frontend.

**Comment by nwaldispuehl** [comment]
To reproduce, build binary with new flags
```
$ sudo go build -o wg-access-server -ldflags="-X 'github.com/freifunkMUC/wg-access-server/buildinfo.Version=v1.2.3' -X 'github.com/freifunkMUC/wg-access-server/buildinfo.CommitHash=1c0ffee'"
```
and run the server:
```
$ sudo ./wg-access-server serve --admin-password=admin --wireguard-interface="wg0" --wireguard-port=51820
```
You will then see the banner in the terminal:
```
INFO[0000]main.go:85 +++ wg-access-server v1.2.3 (1c0ffee)        
INFO[0000]main.go:132 Starting WireGuard on :51820                 
INFO[0000]main.go:147 WireGuard VPN network is ...
...
```
If you additionally start the frontend (`cd website && npm install && npm start`) and login as admin, you can inspect this 'Server Info' structure on the 'All Devices' page:
```
{
  "publicKey": "...",
  "host":

  ...

  "buildInfo": {
    "version": "v1.2.3",
    "commit": "1c0ffee"
  }
}
```
What do you think?

**Review by GoliathLabs — APPROVED** [review]

**Comment by nwaldispuehl** [comment]
> @nwaldispuehl what do you think about these alternative approaches?

Excellent, thanks! :blush: 
These package names as build arguments were indeed asking for trouble.

**Review by fbuetler — APPROVED** [review]
Very nice! 👏🏻

**Comment by nwaldispuehl** [comment]
Hmm, this `github.head_ref` appears to be the wrong variable; it only has content in pull requests as I learned. For the master branch (and presumably tags) it is empty:
```
#85 [linux/amd64 server 14/16] RUN echo "Using: Version: , Commit: 9cbdb4c89cf2bcb8cfcfa2a5b6bf93de1607d863"
#85 0.118 Using: Version: , Commit: 9cbdb4c89cf2bcb8cfcfa2a5b6bf93de1607d863
#85 DONE 0.1s
```
Source: https://github.com/freifunkMUC/wg-access-server/actions/runs/5572919145/jobs/10179510404#step:8:698

:disappointed: 

In the [Github Actions Variables](https://docs.github.com/en/actions/learn-github-actions/variables) page we can also find `GITHUB_REF_NAME` (resp. `github.ref_name`) which might work for the master/main branch and tags, but will produce something undesirable like `3/merge` in pull requests, according to this bug report: https://github.com/github/docs/issues/15319

I'm going to try it with `${{ github.head_ref || github.ref_name }}`.

**Pull request merged**
