### PR TITLE
Rename module to github.com/freifunkMUC/wg-access-server

### PR DESCRIPTION
**Pull request by halkeye**
Right now it'll pull place1's version of code changes.. i think

### CODE REVIEW

**Comment by DasSkelett** [comment]
No it doesn't, otherwise it would be impossible to compile with all the changes we did. It resolves to the packages in our repo because the module has the same name.

That said, IMHO it would make sense to change the module name, now that our changes won't be upstreamed.
This would also allow people to install it using `go install`.

**Comment by halkeye** [comment]
Its been a while since I played with gopath and such, I thought things needed to be in src/GitHub.com/path/to/repo

But maybe go modules changed that

**Comment by DasSkelett** [comment]
Yeah the requirement of being in `$GOPATH/src` is long gone with the introduction of Go Modules in Go 1.11, which deprecated GOPATH:
https://go.dev/blog/using-go-modules
https://go.dev/ref/mod

**Comment by DasSkelett** [comment]
I just merged a bigger PR which created some conflicts, can you rebase the PR?

Also it appears the changes in the protobuf files require a rerun of the codegen commands. I think it changed some sort of file hash. I can take care of that if you want.
If you want to do it yourself it would be those two commands:
```sh
./codegen.sh
cd website && npm run codegen
```
However that requires some protobuf-related packages to be installed on your system.

**Comment by halkeye** [comment]
> ```shell
> ./codegen.sh
> cd website && npm run codegen
> ```

It may want to be made into a docker image or something for version locking?

After installing the exact same version, I'm not actually getting new files generated, so I think its good?

**Comment by DasSkelett** [comment]
Yeah we should probably remove the codegen steps from the default Dockerfile so the build is guaranteed to use the code from the repository, and offer a separate Dockerfile for easy updates.
These are the changes I get when running it locally. The whitespace changes in the frontend files are probably due to an update of one of the npm protobuf packages recently. And while I can't find information about the `file_*_proto_rawDesc` variable, I can imagine that this is some sort of checksum which is different due to the change to the `option go_package` line.

```diff
diff --git a/proto/proto/devices.pb.go b/proto/proto/devices.pb.go
index eb4e223..d3f7387 100644
--- a/proto/proto/devices.pb.go
+++ b/proto/proto/devices.pb.go
@@ -529,10 +529,11 @@ var file_devices_proto_rawDesc = []byte{
 	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x65,
 	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
 	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52,
-	0x65, 0x73, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
-	0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x31, 0x2f, 0x77, 0x67, 0x2d, 0x61, 0x63, 0x63,
-	0x65, 0x73, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
-	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
+	0x65, 0x73, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
+	0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x65, 0x69, 0x66, 0x75, 0x6e, 0x6b, 0x4d, 0x55, 0x43, 0x2f, 0x77,
+	0x67, 0x2d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
+	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
+	0x74, 0x6f, 0x33,
 }
 
 var (
diff --git a/proto/proto/server.pb.go b/proto/proto/server.pb.go
index 92bc8bc..88a2351 100644
--- a/proto/proto/server.pb.go
+++ b/proto/proto/server.pb.go
@@ -203,11 +203,11 @@ var file_server_proto_rawDesc = []byte{
 	0x64, 0x6e, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x32, 0x0a, 0x06, 0x53, 0x65,
 	0x72, 0x76, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x70,
 	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70,
-	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x30,
-	0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61,
-	0x63, 0x65, 0x31, 0x2f, 0x77, 0x67, 0x2d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x73, 0x65,
-	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
-	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
+	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x35,
+	0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x65,
+	0x69, 0x66, 0x75, 0x6e, 0x6b, 0x4d, 0x55, 0x43, 0x2f, 0x77, 0x67, 0x2d, 0x61, 0x63, 0x63, 0x65,
+	0x73, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
+	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
 }
 
 var (
diff --git a/website/src/sdk/devices_pb.ts b/website/src/sdk/devices_pb.ts
index 536fa51..f2892e8 100644
--- a/website/src/sdk/devices_pb.ts
+++ b/website/src/sdk/devices_pb.ts
@@ -167,32 +167,28 @@ export class Device extends jspb.Message {
 	}
 
 
-	getName(): string {
-		return jspb.Message.getFieldWithDefault(this, 1, "");
+	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
 	}
 
 	setName(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 1, value);
 	}
 
-	getOwner(): string {
-		return jspb.Message.getFieldWithDefault(this, 2, "");
+	getOwner(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
 	}
 
 	setOwner(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 2, value);
 	}
 
-	getPublicKey(): string {
-		return jspb.Message.getFieldWithDefault(this, 3, "");
+	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 3, "");
 	}
 
 	setPublicKey(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 3, value);
 	}
 
-	getAddress(): string {
-		return jspb.Message.getFieldWithDefault(this, 4, "");
+	getAddress(): string {return jspb.Message.getFieldWithDefault(this, 4, "");
 	}
 
 	setAddress(value: string): void {
@@ -207,8 +203,7 @@ export class Device extends jspb.Message {
 		(jspb.Message as any).setWrapperField(this, 5, value);
 	}
 
-	getConnected(): boolean {
-		return jspb.Message.getFieldWithDefault(this, 6, false);
+	getConnected(): boolean {return jspb.Message.getFieldWithDefault(this, 6, false);
 	}
 
 	setConnected(value: boolean): void {
@@ -223,48 +218,42 @@ export class Device extends jspb.Message {
 		(jspb.Message as any).setWrapperField(this, 7, value);
 	}
 
-	getReceiveBytes(): number {
-		return jspb.Message.getFieldWithDefault(this, 8, 0);
+	getReceiveBytes(): number {return jspb.Message.getFieldWithDefault(this, 8, 0);
 	}
 
 	setReceiveBytes(value: number): void {
 		(jspb.Message as any).setProto3IntField(this, 8, value);
 	}
 
-	getTransmitBytes(): number {
-		return jspb.Message.getFieldWithDefault(this, 9, 0);
+	getTransmitBytes(): number {return jspb.Message.getFieldWithDefault(this, 9, 0);
 	}
 
 	setTransmitBytes(value: number): void {
 		(jspb.Message as any).setProto3IntField(this, 9, value);
 	}
 
-	getEndpoint(): string {
-		return jspb.Message.getFieldWithDefault(this, 10, "");
+	getEndpoint(): string {return jspb.Message.getFieldWithDefault(this, 10, "");
 	}
 
 	setEndpoint(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 10, value);
 	}
 
-	getOwnerName(): string {
-		return jspb.Message.getFieldWithDefault(this, 11, "");
+	getOwnerName(): string {return jspb.Message.getFieldWithDefault(this, 11, "");
 	}
 
 	setOwnerName(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 11, value);
 	}
 
-	getOwnerEmail(): string {
-		return jspb.Message.getFieldWithDefault(this, 12, "");
+	getOwnerEmail(): string {return jspb.Message.getFieldWithDefault(this, 12, "");
 	}
 
 	setOwnerEmail(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 12, value);
 	}
 
-	getOwnerProvider(): string {
-		return jspb.Message.getFieldWithDefault(this, 13, "");
+	getOwnerProvider(): string {return jspb.Message.getFieldWithDefault(this, 13, "");
 	}
 
 	setOwnerProvider(value: string): void {
@@ -279,7 +268,8 @@ export class Device extends jspb.Message {
 
 	toObject(): Device.AsObject {
 		let f: any;
-		return {name: this.getName(),
+		return {
+			name: this.getName(),
 			owner: this.getOwner(),
 			publicKey: this.getPublicKey(),
 			address: this.getAddress(),
@@ -292,7 +282,6 @@ export class Device extends jspb.Message {
 			ownerName: this.getOwnerName(),
 			ownerEmail: this.getOwnerEmail(),
 			ownerProvider: this.getOwnerProvider(),
-			
 		};
 	}
 
@@ -446,16 +435,14 @@ export class AddDeviceReq extends jspb.Message {
 	}
 
 
-	getName(): string {
-		return jspb.Message.getFieldWithDefault(this, 1, "");
+	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
 	}
 
 	setName(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 1, value);
 	}
 
-	getPublicKey(): string {
-		return jspb.Message.getFieldWithDefault(this, 2, "");
+	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 2, "");
 	}
 
 	setPublicKey(value: string): void {
@@ -470,9 +457,9 @@ export class AddDeviceReq extends jspb.Message {
 
 	toObject(): AddDeviceReq.AsObject {
 		let f: any;
-		return {name: this.getName(),
+		return {
+			name: this.getName(),
 			publicKey: this.getPublicKey(),
-			
 		};
 	}
 
@@ -596,7 +583,7 @@ export class ListDevicesRes extends jspb.Message {
 	setItems(value: Array<Device>): void {
 		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
 	}
-	
+
 	addItems(value?: Device, index?: number): Device {
 		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Device, index);
 	}
@@ -667,8 +654,7 @@ export class DeleteDeviceReq extends jspb.Message {
 	}
 
 
-	getName(): string {
-		return jspb.Message.getFieldWithDefault(this, 1, "");
+	getName(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
 	}
 
 	setName(value: string): void {
@@ -691,9 +677,9 @@ export class DeleteDeviceReq extends jspb.Message {
 
 	toObject(): DeleteDeviceReq.AsObject {
 		let f: any;
-		return {name: this.getName(),
+		return {
+			name: this.getName(),
 			owner: (f = this.getOwner()) && f.toObject(),
-			
 		};
 	}
 
@@ -818,7 +804,7 @@ export class ListAllDevicesRes extends jspb.Message {
 	setItems(value: Array<Device>): void {
 		(jspb.Message as any).setRepeatedWrapperField(this, 1, value);
 	}
-	
+
 	addItems(value?: Device, index?: number): Device {
 		return jspb.Message.addToRepeatedWrapperField(this, 1, value, Device, index);
 	}
diff --git a/website/src/sdk/server_pb.ts b/website/src/sdk/server_pb.ts
index 1dd8fb7..e8ccf96 100644
--- a/website/src/sdk/server_pb.ts
+++ b/website/src/sdk/server_pb.ts
@@ -131,8 +131,7 @@ export class InfoRes extends jspb.Message {
 	}
 
 
-	getPublicKey(): string {
-		return jspb.Message.getFieldWithDefault(this, 1, "");
+	getPublicKey(): string {return jspb.Message.getFieldWithDefault(this, 1, "");
 	}
 
 	setPublicKey(value: string): void {
@@ -147,56 +146,49 @@ export class InfoRes extends jspb.Message {
 		(jspb.Message as any).setWrapperField(this, 2, value);
 	}
 
-	getPort(): number {
-		return jspb.Message.getFieldWithDefault(this, 3, 0);
+	getPort(): number {return jspb.Message.getFieldWithDefault(this, 3, 0);
 	}
 
 	setPort(value: number): void {
 		(jspb.Message as any).setProto3IntField(this, 3, value);
 	}
 
-	getHostVpnIp(): string {
-		return jspb.Message.getFieldWithDefault(this, 4, "");
+	getHostVpnIp(): string {return jspb.Message.getFieldWithDefault(this, 4, "");
 	}
 
 	setHostVpnIp(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 4, value);
 	}
 
-	getMetadataEnabled(): boolean {
-		return jspb.Message.getFieldWithDefault(this, 5, false);
+	getMetadataEnabled(): boolean {return jspb.Message.getFieldWithDefault(this, 5, false);
 	}
 
 	setMetadataEnabled(value: boolean): void {
 		(jspb.Message as any).setProto3BooleanField(this, 5, value);
 	}
 
-	getIsAdmin(): boolean {
-		return jspb.Message.getFieldWithDefault(this, 6, false);
+	getIsAdmin(): boolean {return jspb.Message.getFieldWithDefault(this, 6, false);
 	}
 
 	setIsAdmin(value: boolean): void {
 		(jspb.Message as any).setProto3BooleanField(this, 6, value);
 	}
 
-	getAllowedIps(): string {
-		return jspb.Message.getFieldWithDefault(this, 7, "");
+	getAllowedIps(): string {return jspb.Message.getFieldWithDefault(this, 7, "");
 	}
 
 	setAllowedIps(value: string): void {
 		(jspb.Message as any).setProto3StringField(this, 7, value);
 	}
 
-	getDnsEnabled(): boolean {
-		return jspb.Message.getFieldWithDefault(this, 8, false);
+	getDnsEnabled(): boolean {return jspb.Message.getFieldWithDefault(this, 8, false);
 	}
 
 	setDnsEnabled(value: boolean): void {
 		(jspb.Message as any).setProto3BooleanField(this, 8, value);
 	}
 
-	getDnsAddress(): string {
-		return jspb.Message.getFieldWithDefault(this, 9, "");
+	getDnsAddress(): string {return jspb.Message.getFieldWithDefault(this, 9, "");
 	}
 
 	setDnsAddress(value: string): void {
@@ -211,7 +203,8 @@ export class InfoRes extends jspb.Message {
 
 	toObject(): InfoRes.AsObject {
 		let f: any;
-		return {publicKey: this.getPublicKey(),
+		return {
+			publicKey: this.getPublicKey(),
 			host: (f = this.getHost()) && f.toObject(),
 			port: this.getPort(),
 			hostVpnIp: this.getHostVpnIp(),
@@ -220,7 +213,6 @@ export class InfoRes extends jspb.Message {
 			allowedIps: this.getAllowedIps(),
 			dnsEnabled: this.getDnsEnabled(),
 			dnsAddress: this.getDnsAddress(),
-			
 		};
 	}
 
```

**Review by DasSkelett — APPROVED** [review]
Thank you very much! Looks good, and still compiles :sweat_smile:

**Comment by DasSkelett** [comment]
Okay, `go install` still doesn't work due to the replace directives for wg-embed and pg-events.
```
go: downloading github.com/freifunkMUC/wg-access-server v0.5.3-0.20220304121536-e7c215165c15
go install: github.com/freifunkMUC/wg-access-server@master (in github.com/freifunkMUC/wg-access-server@v0.5.3-0.20220304121536-e7c215165c15):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

Probably makes sense to rename them as well and get rid of the replace directives.

**Pull request merged**
