### PR TITLE
Disable IPv6 by default and auto generate admin password in helm Chart

### LINKED ISSUE #82: Deployment via Helm chart - missing admin password: please set via environment variable, flag or config file
Using the latest Helm chart version `ghcr.io/freifunkmuc/wg-access-server:v0.5.1` and upon boot, the pod crashes with the following:

```
time="2022-01-26T21:18:27Z" level=fatal msg="missing admin password: please set via environment variable, flag or config file" file="main.go:236"
```

My values file is:

```yaml
wireguard:
  config:
    privateKey: "random-20-alpha-numeric-here"

persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - vpn.acme.dev
  tls:
    - hosts:
        - vpn.acme.dev
```

### PR DESCRIPTION
**Pull request by zandemax**
This fixes the issues mentioned in #82 by auto generating an admin password in the helm chart if none is provided, and by disabling IPv6 by default on Kubernetes.

## Problem
Unfortunately, most k8s clusters do not support IPv6 in containers by default, and need some extra configuration on the kubelet to get it to work.
When deploying the helm chart on one of those clusters that does not support IPv6, the creation of the pod fails, because it cannot assign an IPv6 address.

Additionally, the pod also fails to start if the `web.config.adminUsername` value in the helm chart is not provided by the user in their `values.yaml`.
 
## Changes
To make the chart work out of the box on non-IPv6-k8s-clusters (the majority), this PR sets `config.vpn.cidrv6` to `0` by default in `values.yaml`. This disables IPv6 in the wg-access-server and prevents it from failing to start on non-IPv6-clusters.

This PR also adds the helper function `wg-access-server.adminPassword` in `_helpers.tpl`, which checks if `.Values.web.config.adminUsername` is set, and returns it, or otherwise generates a random, 20 characters, alphanumeric password and returns that.
This helper function is then used in `secret.yaml` to set the `adminPassword`.

Additionally, a `NOTES.txt` was added to the helm template, informing the user of the auto generated password and how to retrieve it, should it have been generated upon install.

### CODE REVIEW

**Comment by DasSkelett** [comment]
Thanks! For what I can tell with my very limited Helm & k8s knowledge, this looks good to me.

Two minor things: could you also add a note to the Helm README (`deploy/helm/wg-access-server/README.md`), both about IPv6 being disabled and the auto-generated admin password? Doesn't need to be anything big, just so people are aware what's up.

Maybe something like:
> Because IPv6 on Kubernetes is disabled by default and complicated to enable, the default `values.yaml` disables it for the VPN as well. If you have a cluster with working IPv6, remove the `vpn.cidrv6: 0` section or specify a custom VPN-internal prefix.

and

> If no admin password isn't set, the Chart generates a random one. You can retrieve it using `kubectl get secret ...`

**Comment by zandemax** [comment]
Thanks for the hint, I added two sentences to the README.

**Review by DasSkelett — APPROVED** [review]
LGTM, and `helm lint` didn't report any issues, assuming it would complain if something would be far off with the changes.
@GoliathLabs, I think you mentioned you have used helm in the past, do you want to take a look or two as well?

**Review by GoliathLabs — APPROVED** [review]
Actually @zandemax is a friend of mine who got me in kubernetes in the first place. But I yet have to gather more experience with it though. The PR looks good to me. Thanks for the nice work @zandemax ! <3

**Pull request merged**
