### PR TITLE
Added: Strong admin password generation to default README

### PR DESCRIPTION
**Pull request by GoliathLabs**
This generates a 64 character password by default when used with the `docker run` command. This might be more secure than using `example` in the workflow, since some just copy and paste the command anyway and thus use an insecure admin password.

### CODE REVIEW

**Comment by DasSkelett** [comment]
This won't display the password though, right? And the user won't be able to log in.
We probably need to echo it back.

Also in the case that pwgen isn't installed (most of them, likely), it will effectively be unset and the server will error out with `missing admin password: please set via environment variable, flag or config file`, and the shell should print a "command not found" error above.
But this should hopefully make users realize that they need to either install pwgen, or set their own password.

**Comment by GoliathLabs** [comment]
@DasSkelett I've set a new way to generate a user password. This method should be working on all standard linux systems.

**Comment by DasSkelett** [comment]
Ah, the checks aren't completing because our `paths-ignore`:
https://github.com/freifunkMUC/wg-access-server/blob/a573dadbfce4201594dd4238a7ee43e67a454a2b/.github/workflows/linting.yml#L8-L9

And because of the required status checks we can't merge it. I didn't expect GitHub to be so... dumb. If a workflow isn't triggered on a PR, it should be smart enough not to count it into the required checks.

Judging from multiple thread in the community forum, there isn't a fix for this:
- https://github.community/t/github-actions-and-required-checks-in-a-monorepo-using-paths-to-limit-execution/16586
- https://github.community/t/feature-request-conditional-required-checks/16761

I see two options: run the workflow all the time (doesn't hurt us, just wastes GitHub some computational power), or always wait for an admin, i.e. @awlx, to merge.

**Comment by DasSkelett** [comment]
Apparently GitHub suggests a really ugly hack around this:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

>You can fix this by creating a generic workflow, with the same name, that will return true in any case similar to the workflow below 

Honestly I don't like that, I prefer running the workflow all the time instead.

**Pull request merged**
