### PR TITLE
Updated: Some dependencies

### PR DESCRIPTION
**Pull request by GoliathLabs**
I have updated some nodejs dependencies to the latest available version. React itself takes some time as I have to mess around quite a bit with the code itself.

### CODE REVIEW

**Comment by GoliathLabs** [comment]
P.S. Could one enable "issues" and dependabot warnings so we can fix potential vulnerabilities faster?

**Comment by DasSkelett** [comment]
I think one of the updates breaks something, the UI only shows `loading...` for me, and nothing happens. Does it work for you?

**Comment by DasSkelett** [comment]
Looks like the major upgrade of mobx is what broke things, after reverting those three packages the web UI is working again.

I've also tested them in the following versions (only MINOR updates, not MAJOR), and still works:
```json
    "mobx": "^5.15.7",
    "mobx-react": "^6.3.1",
    "mobx-utils": "^5.6.1",
```

I don't have enough knowledge about mobx or even React to be able to debug the exact cause. I'd say we should go with the above versions until somebody figures out how to make it work with the latest release.

**Comment by DasSkelett** [comment]
I got it working using this `npx mobx-undecorate` tool.
Will push a commit, which also migrates the lockFileVersion from 1 to 2, which should speed up builds and general npm commands, and is backwards compatible to npm 6 and earlier.

**Pull request merged**
